ONG/Noticias/urls.py
from django.urls import path

from . import views

app_name= "edicion_noticias"

urlpatterns = [
    path('admin/edicion', views.ListadoNoticias.as_view(), name= 'admin_edicion_noticias'),
    path('admin/agregar', views.NuevaNoticia.as_view(), name= 'NuevaNoticia'),
]

ONG/ONG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import inicio
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', views.inicio, name='Inicio'),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='Iniciar Sesión'),
    path('logout/', auth_views.logout_then_login, name='Logout'),
    path('noticias/', views.noticias, name='Noticias'),
    
    #url apps
    path('noticias/',  include('Noticias.urls')),
    path('usuarios/',  include('Usuarios.urls')),
]

ONG/Usuarios/urls.py
from django.urls import path

from . import views

app_name= "usuarios"

urlpatterns = [
    path('registro/', views.Registro.as_view(), name= 'Registro'),
]

ONG/Nosotros/models.py
from django.db import models

# Create your models here.

ONG/Noticias/models.py
from django.db import models

class Noticias(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=800)
    fecha = models.CharField ( max_length = 10)
    
    activo= models.BooleanField(default=True)
    
    def __str__(self):
        return self.titulo

ONG/Usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    es_admin = models.BooleanField(default=False)

ONG/Noticias/forms.py
from django import forms
from .models import Noticias

class NoticiaForm(forms.ModelForm):
    class Meta:
        model= Noticias
        fields=["titulo", "descripcion", "fecha", "activo"]
        
        

ONG/Usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class UsuarioForm(UserCreationForm):
    username= forms.CharField(widget= forms.TextInput(attrs={"class": "form-control"}))
    first_name= forms.CharField(widget= forms.TextInput(attrs={"class": "form-control"}))
    last_name= forms.CharField(widget= forms.TextInput(attrs={"class": "form-control"}))
    email= forms.CharField(widget= forms.TextInput(attrs={"class": "form-control"}))
    class Meta:
        model= Usuario
        fields=["username", "first_name", "last_name", "email",]

ONG/Noticias/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from Noticias.models import Noticias
from .forms import NoticiaForm
from django.urls import reverse
'''
def admin_edicion_noticias(request):
    template_name= "Noticias/edicion.html"
    

    contexto= {
        'Noticias': Noticias.objects.all(),
    }
    
    return render(request, template_name, contexto)
'''
class ListadoNoticias(ListView):
    model= Noticias
    template_name= "Noticias/edicion.html"
    context_object_name = 'Noticias'
    paginate_by = 3
    
    def get_queryset(self):
        return Noticias.objects.all().order_by("titulo")
    

class NuevaNoticia(CreateView):
    model= Noticias
    template_name = 'Noticias/nueva_noticia.html'
    form_class= NoticiaForm
    
    def get_success_url(self):
        return reverse("edicion_noticias:admin_edicion_noticias")

ONG/ONG/views.py
from django.shortcuts import render
from django.http import HttpResponse

from Noticias.models import Noticias

def inicio(request):
    template_name= "index.html"
    
    
    return render(request, template_name, {})

def login(request):
    template_name= "login.html"
    #if 'ingresar' in request.POST:
    #    username= request.POST.get("username")
    #if 'ingresar' in request.POST:
    #    username= request.POST.get("password")   
        
    #print(request.method)
    #print(request.POST.get("password", None))
    #print(request.POST.get("username", None))
    return render(request, template_name, {})

def noticias(request):
    template_name= "noticias.html"
    
    #n = Noticias.objects.create(
    #    titulo= "Salvamos un cav",
    #    descripcion= "Hoy encontramos un gato casi muerto y lo salvamos :)",
    #    fecha= "10/11/1000"
    #)
    

    contexto= {
        'Noticias': Noticias.objects.filter(activo=True),
    }
    
    return render(request, template_name, contexto)

ONG/Usuarios/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from Usuarios.models import Usuario
from .forms import UsuarioForm
from django.urls import reverse

class Registro(CreateView):
    model= Usuario
    template_name = 'Usuarios/registro.html'
    form_class= UsuarioForm
    
    def get_success_url(self):
        return reverse("Iniciar Sesión")
    #No pude hacer que vuelva a admin_edicion_noticias

ONG/templates/Noticias/edicion.html
{% extends 'base/base.html' %}

    {% block uno %}
        <div class="row">
            <div class="col">
                <a class="btn btn-primary" href="{% url 'edicion_noticias:NuevaNoticia' %} " role="button">Nueva Noticia</a>
            </div>
        </div>
        
        <div class="card">
            <div class="card-header">
                Lista de Noticias
            </div>
            <div class="card-body">
                <div class="bd-example">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Titulo</th>
                                <th scope="col">Descripción</th>
                                <th scope="col">Imagen</th>
                                <th scope="col">Editar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for Noticias in Noticias %}
                                <tr>
                                    <td>{{Noticias.titulo}}</td>
                                    <td>{{Noticias.descripcion}}</td>
                                    <td>{{Noticias.imagen}}</td>
                                    <td>
                                        <button type="button" class="btn btn-danger">Eliminar</button>
                                        <button type="button" class="btn btn-warning">Modificar</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
            
                    </table>
                </div>
            </div>
        </div>

        {% if is_paginated %}
            <nav>
                <ul class="pagination pagination-circle mg-b-0 justify-content-center">
                    {% if page_obj.number == 1  %}
                        <li class="page-item disabled"><a class="page-link">primera</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page=1">primera</a></li>
                    {% endif %}
                    
                    
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">anterior</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link">anterior</a></li>
                    {% endif %}

                    {% for i in paginator.page_range %}
                        {% if page_obj.number|add:'-1' <= i and page_obj.number|add:'1' >= i %}
                            <li class="page-item {% if page_obj.number == i %}active{% endif %}"><a class="page-link" href="?page={{i}}">{{ i }}</a></li>
                        {% else %}

                        {% endif %}
                    {% endfor %}
                    
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">siguiente</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link">siguiente</a></li>
                    {% endif %}

                    {% if page_obj.number == paginator.num_pages %}
                        <li class="page-item disabled"><a class="page-link">ultima</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{paginator.num_pages}}">ultima</a></li>
                    {% endif %}  
                </ul>
            </nav>	
        {% endif %}

        <a class="btn btn-primary" href="{% url 'Noticias' %} " role="button">Volver</a>
    {% endblock uno %}

ONG/templates/Noticias/nueva_noticia.html
{% extends 'base/base.html' %}

    {% block uno %}
        <form method="post"> {% csrf_token %}
            {{form.as_p}}
            <p><button class="w-100 btn btn-lg btn-primary" type="submit" href="{% url 'edicion_noticias:admin_edicion_noticias' %} " name="Agregar">Agregar</button></p>
        </form>
    {% endblock uno %}

ONG/templates/Usuarios/registro.html
{% extends 'base/base.html' %}

    {% block uno %}
        <div class="card">
            <div class="card-body">
                <form method="post"> {% csrf_token %}
                    {{form.as_p}}
                    <p><button class="w-100 btn btn-lg btn-primary" type="submit" name="Registrarme">Registrarme</button></p>
                    <p></p><a class="w-100 btn btn-lg btn-primary" href=" {% url 'Inicio' %} ">Volver al Inicio</a></p>
                </form>
            </div>
        </div>
    {% endblock uno %}

ONG/templates/base/base.html
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.104.2">
        <title>Mi Bella Ciudad</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/navbar-fixed/">

        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

        

    <link href="/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

        <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


        <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
            font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
        </style>

        
        <!-- Custom styles for this template -->
        <link href="navbar-top-fixed.css" rel="stylesheet">
</head>
<body>
    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <div
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
    </div>
    

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
        <p class="navbar-brand" >Mi Bella Ciudad</p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href=" {%url 'Inicio'%} ">Nosotros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href=" {%url 'Noticias'%} ">Noticias</a>
                </li>
            </ul>
            <form class="d-flex" role="search">

                {% if user.is_authenticated %}
                    <a class="w-50% btn btn-xs btn-primary btn-block d-flex" href=" {% url 'Logout' %} ">Cerrar Sesión</a>
                {% else %}
                    <a class="w-50% btn btn-xs btn-primary btn-block d-flex" style="background-color: #E74C3C; border-color: #E74C3C ;" href=" {% url 'Iniciar Sesión' %} ">Iniciar Sesión</a>
                    <a class="w-50% btn btn-xs btn-primary btn-block d-flex" style="background-color: #3498DB ; border-color: #3498DB;" href="{% url 'usuarios:Registro' %}">Registrarme</a>
                {% endif %}

            </form>
        </div>
        </div>
    </nav>
    
    {% block uno %}

    {% endblock uno %}
    
    
    <script src="/docs/5.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

        
    

</body>
</html> 

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Mi Bella Ciudad </title>

    <!-- CSS -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<!--
<ul> 
{% for noticia in Noticias %}
    <li>{{ noticia.titulo }}</li>
    <li>{{ noticia.imagen }}</li>
{% endfor %}
</ul> -->


    <!-- JS -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

ONG/templates/noticias.html
{% extends 'base/base.html' %}

    {% block uno %}

            {% for Noticias in Noticias %}
                <div class="card">
                    <div class="card-body">
                    <h5 class="card-title">{{Noticias.titulo}}</h5>
                    <p class="card-text">{{Noticias.descripcion}}</p>
                    <p class="card-text"><small class="text-muted">{{Noticias.fecha}}</small></p>
                </div>
            {% endfor %}

        <a class="btn btn-primary" href="{% url 'edicion_noticias:admin_edicion_noticias' %} " role="button">Editar</a>
    {% endblock uno %}